spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:5432/data_labeling_db
spring.datasource.username=postgres
spring.datasource.password=123456

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


# JWT Config
app.jwt.secret=7d64b07f2ef8c72bd7dfa8baefce8d7b3858c8c5c4146e5b0b1bc676db7a6021bbd843105a3977c7f999990885e3f4369e9a263ba0e8d08502f6dc4d3b6f0e30
app.jwt.expiration=86400000
